### ISSUE TITLE
Updating readme files for all the projects

### ISSUE THREAD

**Issue by s-dabral** [OpenCodeEra/ML-X#1]
## Your LinkedIn profile - https://www.linkedin.com/in/suyash-dabral-664011195/

Hey @AdarshRawat1 , 
There is no readme files for any of the projects section in the repository.
Please assign me that.

**Comment by AKACHI-4** [comment]
Hey @s-dabral... actually the notebooks over there for each of the model will be well-documented. so you don't have to worry about it .. btw we'll encourage you to check [Contributing.md](https://github.com/OpenCodeEra/ML-X/blob/main/CONTRIBUTING.md) by tommorow to get idea for contribution.
