### ISSUE TITLE
Regarding new models

### ISSUE THREAD

**Issue by s-dabral** [OpenCodeEra/ML-X#17]
Hey @AKACHI-4 ,  as you've written that we can also include other basic or advanced models in the repo, I do have some basic level ML models which can be included in the repository for future benefits.

Can I start a PR for this ?

**Comment by AKACHI-4** [comment]
Hey @s-dabral, I'm happy that you want to contribute some models. Kindly create a new issue and describe the model, dataset, and algorithm you'd like to contribute.

also, we encourage contributors to focus on a single model now. so we can maximize the insights from both the dataset and the model.
